# Generated by Django 2.2.16 on 2022-10-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20221006_2208'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow_exists',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='self follow is not accessed',
        ),
    ]
